version: '3.7'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./:/code
    ports:
      - 5000:5000
    container_name: python_app
